### ISSUE TITLE
Add reference, search for existing reference not working

### ISSUE THREAD

**Issue by lizadams** [lizadams/emf#13]
76. To add a new reference to the control measure, click Add in the References tab, and the Add Reference Record window will appear (Figure). You will need to either choose a reference that already exists in the database, or add a new reference.

To choose an existing reference, click on the Use existing reference option and then search for the reference by filling in the Text contains field, then click Search. When you have located the correct reference, select the reference, and click Save to add the reference. For this step, a new reference will be created instead of adding an existing one. The next paragraph explains how to create a new reference.

Click on Use existing reference
Text contains: MACTEC
A search on MACTEC, didn't work.

Is it possible that the list of references has changed, and those used in the 
Control Measure: Selective Non-Catalytic Reduction: ICI Boilers - Natural Gas and Oil
as the list of references is no longer in the database?

A search on COST was successful, with two references displayed.

**Comment by cseppan** [comment]
There's a bug searching for capitalized terms. It'll be fixed in EMF v2.15 (https://github.com/USEPA-OAQPS/emf/issues/18).
