### ISSUE TITLE
Filter by Description isn't an option

### ISSUE THREAD

**Issue by lizadams** [lizadams/emf#15]
92. Click Find again and this time, enter a filter on the Select SCCs dialog based on the SCC description instead of the SCC itself. For example, use the Filter Rows button on the toolbar to enter the filter Description contains Cement, then click on the checkbox in the Select column for a few of these SCCs (e.g., 30500606) and click OK. If there are measures in the database for the selected SCCs, they will be shown in the Control Measure Manager table. However, note that there may be some SCCs for which there are no measures available in the database. In that case, no measures would be shown in the table after you apply your filter. For the measures that are returned, notice whether they all have the same value for Pollutant (e.g., measures for SCC 30500606 target NOx, PM10, and SO~2).

Column names include "Name, Abbreviation, Pollutant, Sector, Class"
![filter_by_column_name](https://user-images.githubusercontent.com/1183863/28138319-5d21eb72-671e-11e7-8839-469485a37877.png)

**Comment by cseppan** [comment]
In the screenshot, you're applying filter criteria to the Control Measure Manager window, not the Select SCCs dialog. When you filter the Select SCCs list, you'll see "description" as a column option.

<img width="481" alt="screen shot 2017-08-04 at 5 35 31 pm" src="https://user-images.githubusercontent.com/7329179/28987907-6492d482-793b-11e7-9152-4afbe3f80ed0.png">

**Comment by lizadams** [comment]
This is my error.  Closing this as an issue
