### ISSUE TITLE
is the default cost YEAR still 2013?

### ISSUE THREAD

**Issue by lizadams** [lizadams/emf#17]
Under the section The Cost Year Menu
The **Cost Year** menu near the bottom of the Control Measure Manager controls the cost year for which the cost data are shown in the manager. The default cost year is 2013.
Using the v2.14 version I can see years 1999-2014

**Comment by cseppan** [comment]
Yes, as of EMF v2.14, the default cost year is 2013. The system has data for cost years through 2016, but the cost year menu is static and needs to be updated. I added an issue to the master EMF list: https://github.com/USEPA-OAQPS/emf/issues/17

**Comment by lizadams** [comment]
In this section of the documentation it says to use 2006 for the Cost Year.  I am going to update this to use 2013, as I think the 2006 used in the documentation is out of date.

15. Specify a Cost Year to use for presenting the costs for the results of this strategy. For training purposes, enter 2006. All cost data specified for the control measures will be converted to this year using the Gross Domestic Product (GDP): Implicit Price Deflator (IPD), issued by the U.S. Department of Commerce, Bureau of Economic Analysis. Details of the computation used are given in the "Control Strategy Tool (CoST) Development Document". Note that there is a 1- to 2-year lag between the current year and the latest available data, so you cannot specify the current year in this field.

**Comment by lizadams** [comment]
in the cost_guide.md exercise: 5.3 Running a Strategy with a Hypothetical Measure
It says to use a cost year of 2006, should this be updated to 2013? - May need to redo this exercise to see what impact it has, if the date is changed.
