### ISSUE TITLE
control strategy manager - list of algorithms

### ISSUE THREAD

**Issue by lizadams** [lizadams/emf#20]
Documentation currently lists 6 algorithms
Version 2.13 only has 4 algorithms
version 2.14 has the 4 algorithms in 2.13 and additional algorithms. 
Does the documentation need to be updated to describe all of the algorithms?

![control_strategy_algorithms_v214](https://user-images.githubusercontent.com/1183863/28637890-19c9c784-7211-11e7-86b1-bf30a6278ef2.png)

Annotate Inventory (not available)
Apply Measures in Series (not available)
Least Cost  (v2.13, v2.14)
Least Cost Curve (v2.13, v2.14)
Maximum Emissions Reduction (v2.13, v2.14)
Multi-Pollutant Maximum Emissions Reduction (v2.13, v2.14)

**Comment by cseppan** [comment]
Each control strategy specifies the type of analysis to perform, aka the algorithm to use. The all-in-one package comes with a few control strategies already defined, which are examples of the Least Cost and Max Reduction algorithms. The UNC EMF server has many more control strategies created, for various testing purposes.
