### ISSUE TITLE
no inventories available

### ISSUE THREAD

**Issue by lizadams** [lizadams/emf#23]
In the following step of the Control Strategy Manager documentation: 
26. To select an inventory to use for the strategy from the dialog, click on the name of the inventory with your mouse. For training purposes, select nonpt_pf4_cap_nopfc_2017ct_nc_sc_va and then click OK. When you return to the Inventories tab, you will see the inventory you selected in the list of inventories to process.

I am not seeing an inventory available to choose from.
![inventories_tab_of_edit_control_strategy_window](https://user-images.githubusercontent.com/1183863/29085375-1996a1c0-7c3d-11e7-8808-99a6b38b4645.png)

**Comment by lizadams** [comment]
I first needed to add the dataset.. Closing this issue

**Comment by lizadams** [comment]
ok - the described ORL Nonpoint datasets don't exist. 
I only see datasets under the Flat File 2010 NonPoint and Flat File 2010 Point
![flat_file_2010_nonpoint](https://user-images.githubusercontent.com/1183863/29085788-5af7277e-7c3e-11e7-8422-ebdd0129ddf8.png)
![flat_file_2010_point](https://user-images.githubusercontent.com/1183863/29085791-5d85fcf4-7c3e-11e7-9087-c55c4bb9900d.png)

**Comment by cseppan** [comment]
For the all-in-one package, we upgraded the example inventories to use newer FF10 based data. So the training needs to be updated to use those inventories in place of the old ORL inventories.

**Comment by lizadams** [comment]
Changed the documentation to use the new FF10 datasets.
