### ISSUE TITLE
sort order contains invalid column: ann_emis, fips

### ISSUE THREAD

**Issue by lizadams** [lizadams/emf#24]
e.g., "ANN_EMIS desc, FIPS" will sort by decreasing annual emissions and then by county.
This doesn't work.  It looks like ANN_EMIS is not ANN_VALUE ?
Should I use REGION_CD  instead of FIPS?

**Comment by cseppan** [comment]
Yes, the column names are different for FF10 datasets vs. ORL. So switch to ANN_VALUE and REGION_CD.

**Comment by lizadams** [comment]
How do I translate this to an example that can be used

Filter sources only in NC (State FIPS = 37), SC (45), and VA (51);note that FIPS column format is State + County FIPS code (e.g., 37001) | substring(FIPS,1,2) in ('37', '45', '51')
-- | --

It looks like the REGION_CD only has values starting with 37, is that equivalent to the FIPS

**Comment by cseppan** [comment]
You can replace the column name FIPS with REGION_CD:

substring(REGION_CD,1,2) in ('37', '45', '51')
