### ISSUE TITLE
Control Measure, format columns - missing Numeric Format Option

### ISSUE THREAD

**Issue by lizadams** [lizadams/emf#7]
The Format Columns window no longer has the Numeric Format Option component (see attached image).
  
This is the image from v2.13:
https://github.com/lizadams/emf/blob/master/EMF/deploy/doc/guides/cost/images/Format_Columns_Dialog.png
  
Is that correct?
  
If so, I will need to edit step 19  https://github.com/lizadams/emf/blob/master/EMF/deploy/doc/guides/cost/ch3_control_measure_manager.md
to remove the following:
  
and the number of Decimal Places to 0, and select significant digits
  
“In practice, this dialog is not used very often, but it can be particularly helpful to format numeric data by changing the number of decimal places or the number of significant digits shown.”
  
![format_columns_dialog](https://user-images.githubusercontent.com/1183863/28129495-8214ac70-6701-11e7-9e75-cfdb4b5f40c9.png)

**Comment by cseppan** [comment]
The format options are only displayed when one or more columns are selected via the checkbox in the Format? column.

**Comment by lizadams** [comment]
ok - I understand now.
